#include "uart.h"

void uart0_init() {
  //GPIO_REG(GPIO_IOF_SEL) &= ~IOF0_UART0_MASK;
  //GPIO_REG(GPIO_IOF_EN) |= IOF0_UART0_MASK;
  //UART0_REG(UART_REG_DIV) = 1000000 / SIFIVE_UART_DEFUALT_BAUD_RATE - 1;
  UART0_REG(UART_REG_TXCTRL) |= UART_TXEN;
}
